# Docker Compose 文件版本
version: '3.8'

# 定义服务
services:
  # 服务的名字，可以自定义
  litellm-proxy:
    # 使用官方提供的 LiteLLM 镜像
    image: litellm/litellm:v1.75.5-stable

    # 给容器起一个好记的名字
    container_name: litellm-proxy

    # 将我们存放 API Keys 的 .env.litellm 文件加载到容器中作为环境变量
    env_file:
      - .env.litellm

    # 端口映射: 将主机的 4000 端口映射到容器的 4000 端口
    # 格式: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "7203:4000"

    # 卷挂载: 将我们本地的配置文件挂载到容器内部
    # 这样我们修改本地的 config.yaml 后，只需重启容器即可生效，无需重建镜像
    # 格式: "HOST_PATH:CONTAINER_PATH"
    volumes:
      - ./config.yaml:/app/config.yaml

    # 容器启动后要执行的命令
    # 这等同于我们在终端里运行 'litellm --config ...'
    command: >
      --config /app/config.yaml 
      --host 0.0.0.0 
      --port 4000

    # 推荐的设置：如果容器停止，自动重启
    restart: unless-stopped
